# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61i.proto\x12\x02\x61i\"#\n\x10\x41nalyzeCVRequest\x12\x0f\n\x07\x63v_text\x18\x01 \x01(\t\"\x7f\n\x12\x43VAnalysisResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\x12\x16\n\x0erecommendation\x18\x02 \x01(\t\x12\x0e\n\x06skills\x18\x03 \x03(\t\x12\x1d\n\x15\x65xperience_highlights\x18\x04 \x03(\t\x12\x11\n\tfit_score\x18\x05 \x01(\x05\"3\n\x0fMatchJobRequest\x12\x0f\n\x07\x63v_text\x18\x01 \x01(\t\x12\x0f\n\x07jd_text\x18\x02 \x01(\t\"w\n\x10JobMatchResponse\x12\r\n\x05score\x18\x01 \x01(\x05\x12\x16\n\x0ematched_skills\x18\x02 \x03(\t\x12\x16\n\x0emissing_skills\x18\x03 \x03(\t\x12\x13\n\x0b\x65xplanation\x18\x04 \x01(\t\x12\x0f\n\x07verdict\x18\x05 \x01(\t2}\n\tAIService\x12\x39\n\tAnalyzeCV\x12\x14.ai.AnalyzeCVRequest\x1a\x16.ai.CVAnalysisResponse\x12\x35\n\x08MatchJob\x12\x13.ai.MatchJobRequest\x1a\x14.ai.JobMatchResponseB\x1dZ\x1bworkzen-be/internal/grpc/aib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\033workzen-be/internal/grpc/ai'
  _globals['_ANALYZECVREQUEST']._serialized_start=16
  _globals['_ANALYZECVREQUEST']._serialized_end=51
  _globals['_CVANALYSISRESPONSE']._serialized_start=53
  _globals['_CVANALYSISRESPONSE']._serialized_end=180
  _globals['_MATCHJOBREQUEST']._serialized_start=182
  _globals['_MATCHJOBREQUEST']._serialized_end=233
  _globals['_JOBMATCHRESPONSE']._serialized_start=235
  _globals['_JOBMATCHRESPONSE']._serialized_end=354
  _globals['_AISERVICE']._serialized_start=356
  _globals['_AISERVICE']._serialized_end=481
# @@protoc_insertion_point(module_scope)
