# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/ai_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/ai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/ai_service.proto\x12\nai_service\"!\n\x0e\x41nalyzeRequest\x12\x0f\n\x07\x63v_text\x18\x01 \x01(\t\"|\n\x0f\x41nalyzeResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\x12\x16\n\x0erecommendation\x18\x02 \x01(\t\x12\x0e\n\x06skills\x18\x03 \x03(\t\x12\x1d\n\x15\x65xperience_highlights\x18\x04 \x03(\t\x12\x11\n\tfit_score\x18\x05 \x01(\x05\"0\n\x0cMatchRequest\x12\x0f\n\x07\x63v_text\x18\x01 \x01(\t\x12\x0f\n\x07jd_text\x18\x02 \x01(\t\"t\n\rMatchResponse\x12\r\n\x05score\x18\x01 \x01(\x05\x12\x16\n\x0ematched_skills\x18\x02 \x03(\t\x12\x16\n\x0emissing_skills\x18\x03 \x03(\t\x12\x13\n\x0b\x65xplanation\x18\x04 \x01(\t\x12\x0f\n\x07verdict\x18\x05 \x01(\t2\x95\x01\n\tAIService\x12\x46\n\tAnalyzeCV\x12\x1a.ai_service.AnalyzeRequest\x1a\x1b.ai_service.AnalyzeResponse\"\x00\x12@\n\x07MatchCV\x12\x18.ai_service.MatchRequest\x1a\x19.ai_service.MatchResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZEREQUEST']._serialized_start=38
  _globals['_ANALYZEREQUEST']._serialized_end=71
  _globals['_ANALYZERESPONSE']._serialized_start=73
  _globals['_ANALYZERESPONSE']._serialized_end=197
  _globals['_MATCHREQUEST']._serialized_start=199
  _globals['_MATCHREQUEST']._serialized_end=247
  _globals['_MATCHRESPONSE']._serialized_start=249
  _globals['_MATCHRESPONSE']._serialized_end=365
  _globals['_AISERVICE']._serialized_start=368
  _globals['_AISERVICE']._serialized_end=517
# @@protoc_insertion_point(module_scope)
